_wandb:
    value:
        cli_version: 0.24.0
        e:
            gb65sjmfnb08a2pplpcwlyuaauqhhajv:
                apple: {}
                args:
                    - --input_artifact
                    - raw_data.parquet:latest
                    - --artifact_name
                    - preprocessed_data.csv
                    - --artifact_type
                    - preprocessed_data
                    - --artifact_description
                    - Data is preprocessed
                codePath: preprocess/run.py
                codePathLocal: run.py
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "494384795648"
                        used: "241013805056"
                email: yearofnoexcuses@gmail.com
                executable: /Users/samroska/github/genre_classification/.venv/bin/python
                git:
                    commit: 73a579102f75a67b4d6265a7de6ab5b2705cce74
                    remote: git@github.com:samroska/genre_classification.git
                host: pyrite.local
                memory:
                    total: "17179869184"
                os: macOS-26.3.1-arm64-arm-64bit-Mach-O
                program: /Users/samroska/github/genre_classification/preprocess/run.py
                python: CPython 3.13.3
                root: /Users/samroska/github/genre_classification/preprocess
                startedAt: "2026-05-24T03:02:31.156298Z"
                writerId: gb65sjmfnb08a2pplpcwlyuaauqhhajv
        m: []
        python_version: 3.13.3
        t:
            "4": 3.13.3
            "5": 0.24.0
            "12": 0.24.0
            "13": darwin-arm64
